### ISSUE TITLE
training error with smaller images (96x96)

### ISSUE THREAD

**Issue by zabir-nabil** [csbhr/CDVD-TSP#10]
I'm trying to train your model on a very small frames (96 by 96). I'm getting following error while training:

```
(cdvd-tsp) vmuser@a87bb9983200:~/Data/denoising/CDVD-TSP/code$ python main.py --save ../lp_results --dir_data ../lp_train --dir_data_test ../lp_test --epochs 500 --batch_size 5
Save Path : ../experiment/../lp_results
Selected task: VideoDeblur
Making model...
Creating CDVD-TSP Net
Is meanfilter image when process mask: True
Select mask mode: concat, num_mask=1
Creating Flow PWC
Loading Flow PWC pretrain model from ../pretrain_models/network-default.pytorch
Creating Recons-Video Net
SRN Video Net extra in channels: 1
The input of SRN is image
Preparing loss function:
1.000 * L1
2.000 * HEM
n_seq: 5
n_frames_per_video: 100
Loading train => DVD DataSet
DataSet gt path: ../lp_train/gt
DataSet blur path: ../lp_train/blur
Number of videos to load: 12
Number of frames to load: 303
Dataset repeat: 16
n_seq: 5
n_frames_per_video: 100
Loading test => DVD DataSet
DataSet gt path: ../lp_test/gt
DataSet blur path: ../lp_test/blur
Number of videos to load: 3
Number of frames to load: 18
Using Trainer-CDVD-TSP
Now training
Epoch   1 with Lr 1.00e-4
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    t.train()
  File "/home/vmuser/Data/denoising/CDVD-TSP/code/trainer/trainer_cdvd_tsp.py", line 34, in train
    for batch, (input, gt, _) in enumerate(self.loader_train):
  File "/home/vmuser/anaconda3/envs/cdvd-tsp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/vmuser/anaconda3/envs/cdvd-tsp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/home/vmuser/anaconda3/envs/cdvd-tsp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/vmuser/anaconda3/envs/cdvd-tsp/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/home/vmuser/Data/denoising/CDVD-TSP/code/data/videodata.py", line 95, in __getitem__
    inputs_concat, gts_concat = self.get_patch(inputs_concat, gts_concat, self.args.size_must_mode)
  File "/home/vmuser/Data/denoising/CDVD-TSP/code/data/videodata.py", line 153, in get_patch
    input, gt = utils.get_patch(input, gt, patch_size=self.args.patch_size)
  File "/home/vmuser/Data/denoising/CDVD-TSP/code/utils/utils.py", line 17, in get_patch
    ix = random.randrange(0, iw - ip + 1)
  File "/home/vmuser/anaconda3/envs/cdvd-tsp/lib/python3.6/random.py", line 199, in randrange
    raise ValueError("empty range for randrange() (%d,%d, %d)" % (istart, istop, width))
ValueError: empty range for randrange() (0,-159, -159)

```

**Comment by csbhr** [comment]
The patch-size of the training code is 256*256, which means the training image's size should larger than 256.

You can modify the patch-size parameter in ./code/option/__init__.py

**Comment by zabir-nabil** [comment]
Thanks, that worked.
