### ISSUE TITLE
when I test model on my data,happen one error

### ISSUE THREAD

**Issue by dayu1979** [csbhr/CDVD-TSP#12]
Loading model from ../pretrain_models/CDVD_TSP_DVD_Convergent.pt
Traceback (most recent call last):
  File "inference.py", line 243, in <module>
    Infer.infer()
  File "inference.py", line 123, in infer
    self.logger.write_log("# Total AVG-PSNR={:.5}, AVG-SSIM={:.4}".format(sum_psnr / n_img, sum_ssim / n_img))
ZeroDivisionError: float division by zero

**Comment by Michaelwhite34** [comment]
I have the same error- -

**Comment by Etienne66** [comment]
I fixed this issue in my fork. Basically it is because you do not have any GT images. You can copy your blurry images to the GT folder. It just won't have a good PSNR calculated. My fix was not to calculate it if there were no GT images.
