### ISSUE TITLE
AttributeError: module 'cupy' has no attribute 'util'

### ISSUE THREAD

**Issue by jpiabrantes** [csbhr/CDVD-TSP#35]
When running `inference.py`:

```sh
Traceback (most recent call last):
  File "/home/ubuntu/github/CDVD-TSP/code/model/flow_pwc.py", line 10, in <module>
    from model import correlation
  File "/home/ubuntu/github/CDVD-TSP/code/model/correlation.py", line 282, in <module>
    @cupy.util.memoize(for_each_device=True)
  File "/home/ubuntu/anaconda3/envs/deblur37/lib/python3.7/site-packages/cupy/__init__.py", line 875, in __getattr__
    f"module 'cupy' has no attribute {name!r}")
AttributeError: module 'cupy' has no attribute 'util'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "inference.py", line 10, in <module>
    from model.cdvd_tsp import CDVD_TSP
  File "/home/ubuntu/github/CDVD-TSP/code/model/cdvd_tsp.py", line 4, in <module>
    from model import flow_pwc
  File "/home/ubuntu/github/CDVD-TSP/code/model/flow_pwc.py", line 13, in <module>
    import correlation  # you should consider upgrading python
ModuleNotFoundError: No module named 'correlation'
```

**Comment by csbhr** [comment]
This error is related to the version of the package "cupy".

You can fix this error by modifying line282 in the file "./code/model/correlation.py":
"@cupy.util.memoize(for_each_device=True)" -> "@cupy.memoize(for_each_device=True)"
